### ISSUE TITLE
Multiple host failover failure

### ISSUE THREAD

**Issue by jhiggins-bam** [awslabs/aws-postgresql-jdbc#59]
**Describe the issue**

When providing multiple hosts in the url, the driver does not fail over to the next host in the url.

**Driver Version?** 

0.1.0

**Java Version?**

11.0.7

**OS Version?**

OSX 10.14.6

**PostgreSQL Version?**

Aurora postgresql 13.4

**To Reproduce**

Use a connection string such as:

```
jdbc:postgresql:aws://myauroracluster.cluster-example.us-east-1.rds.amazonaws.com:5432,
myauroracluster.cluster-example.us-west-2.rds.amazonaws.com:5432
/postgres?user=<primaryuser>&password=<primarypw>&loginTimeout=2
&connectTimeout=2&cancelSignalTimeout=2&socketTimeout=60
&tcpKeepAlive=true&targetServerType=secondary
```

Set up a global RDS aurora cluster such that the cluster in us-east-1 has 1 writer nodes and 0 readers, and the cluster in 
us-west-2 has 1 reader node and 0 writers (i.e. a global RDS cluster where us-east-1 is the primary region).

**Expected behaviour**

When providing a `targetServerType` such as secondary, if the driver finds no secondary nodes in the leftmost host provided,
(in the above example `myauroracluster.cluster-example.us-east-1.rds.amazonaws.com`), it should connect to `myauroracluster.cluster-example.us-west-2.rds.amazonaws.com` where a secondary node can be found. 

This is the behavior of the pgjdbc driver, which does successfully fail over in this case.

However this driver does not fail over, and exits with an error after trying the first host.

Only when using fast-failover mode does this occur (i.e. `jdbc:postgresql:aws:`), when using the driver with fast-failover disabled, the expected behavior prevails. 

**Logs**

[Logs pastebin here](https://pastebin.com/wjLkrZ4D)

**Comment by hsuamz** [comment]
Hello @jhiggins-bam,

Thanks for reaching out and trying the AWS JDBC Driver for PostgreSQL.

Fast failover for global RDS Aurora clusters are not supported right now. It is a feature in our backlog that we'll be looking into. Since fast failover relies on the cluster topology, it ignores additional hosts in the connection string.

Please let us know if you any questions regarding this.

Thanks,

Matthew

**Comment by jhiggins-bam** [comment]
Thank you Matthew for the information.
