### ISSUE TITLE
Version 0.2.0 needs to be published to Maven Central

### ISSUE THREAD

**Issue by Sovietaced** [awslabs/aws-postgresql-jdbc#60]
The README references gradle dependency statements with version 0.2.0, however the latest version uploaded to Maven Central is 0.1.0: https://search.maven.org/search?q=a:aws-postgresql-jdbc. 

Can the latest version of this library please be published to Maven Central?

**Comment by hsuamz** [comment]
Thanks for reaching out @Sovietaced.

We'll revert the documentation to point to 0.1.0. We held off providing an updated release to ensure we're following the community's approach with the authentication plugin.

Are there specific features or fixes on our mainline branch that you need that 0.1.0 does not include?

Thanks,

Matthew

**Comment by Sovietaced** [comment]
> Are there specific features or fixes on our mainline branch that you need that 0.1.0 does not include?

Not in particular
