### ISSUE TITLE
Typo in document

### ISSUE THREAD

**Issue by graben1437** [awslabs/aws-postgresql-jdbc#62]
The document at this header:   Using the AWS JDBC Driver for PostgreSQL. states that:

The AWS JDBC Driver for MySQL is drop-in compatible, so usage is identical to the PostgreSQL JDBC Driver.

I believe that should read "AWS JDBC Driver for Postgres" ?

**Comment by ColinKYuen** [comment]
Hi @graben1437 ,

Thanks for bringing this up. Taking another look, we noticed another typo similar to the one you found regarding AWS IAM. We'll fix those issues in the documentation.

Thanks again for the feedback!

Cheers,

Colin
