### ISSUE TITLE
big decimal read breaks after 5 reads

### ISSUE THREAD

**Issue by TonyMcTony** [awslabs/aws-postgresql-jdbc#67]
**Describe the issue**
if you have a numeric column in a postgres table with a value of 20000 and you read it 5 times on the 5th read it will read it as 2 instead of 20000.

Basically, it's this issue, which was fixed in more recent versions of pgjdbc driver: https://github.com/pgjdbc/pgjdbc/issues/2326

**Driver Version?** 
0.1.0

**Java Version?**
17

**OS Version?**
MacOS/Linux/Kubernetes
**PostgreSQL Version?**
12.8

**Comment by semirenko** [comment]
this issue is basically a showstopper for us

**Comment by hsuamz** [comment]
For visibility, we are recommending everyone to move to our new repository here: https://github.com/awslabs/aws-advanced-jdbc-wrapper.

We have redesigned the driver as a JDBC Wrapper which has been tested to work with the PGJDBC driver. Please give it a look and we will be triaging issues in the new repository.

Thanks.
