### ISSUE TITLE
Support for Amazon Aurora Global Database?

### ISSUE THREAD

**Issue by Sovietaced** [awslabs/aws-postgresql-jdbc#70]
Hello. We've been using this library for a few months now in production and it has worked well for our single cluster Aurora PostgreSQL deployment. Our applications are no longer bricked with cached, read-only DB connections for 30 minutes when a failover happens which is great! 

We're looking to make our applications more robust to regional failures so we are now transitioning to using Aurora's Global Database offering. It appears that this library is not really compatible with Aurora's Global Database since the topology discovering is implemented by querying a table that is scoped to a single Aurora cluster. 

I was wondering if support for this is being worked on or not. Since we have immediate needs to support Aurora's Global Database I have forked this repository and added support by implementing topology discovery using AWS RDS APIs. Considering that this library is architected in a manner that assumes topology discover is done using DB connections there is some architectural fallout but I'm wondering if you might be interested in such a contribution. 

Thanks

**Comment by sergiyvamz** [comment]
Hello @Sovietaced 

We're glad to hear that the driver made your application more robust and stable! Thank you for your trust in the driver and giving it a chance to work in a production system!

You're absolutely right that Aurora Global Databases isn't currently supported by the driver. This feature is in our backlog and was originally intended to be included in a future release. We're glad to hear that you made your own implementation of this feature and we are open if you wanted to contribute it back to the community.

For your awareness, we have recently launched the [AWS Advanced JDBC Driver with PostgreSQL Support](https://github.com/awslabs/aws-advanced-jdbc-wrapper). Going forward, all active JDBC development will be carried out here and we will be encouraging everyone to move here. We can definitely work with you around Aurora Global Database support and how that can integrate with the new driver.

Thank you!

**Comment by Sovietaced** [comment]
Sounds good. I'll take a look at the new architecture and dig in.
