### ISSUE TITLE
useAWSIam is not working 

### ISSUE THREAD

**Issue by layshah72** [awslabs/aws-postgresql-jdbc#76]
I am setting the jdbc connection property in spring boot as below

spring.datasource.url=jdbc:postgresql:aws://xx-database.cluster.eu-west-1.rds.amazonaws.com:5432/mydb;useAwsIam=true

but it is not giving any effect and server is refusing connection as it is expecting password

**Comment by davecramer** [comment]
Hello, 

I would suggest that you try https://github.com/awslabs/aws-advanced-jdbc-wrapper
